defmodule Wayfinder.Typescript.Helpers do
  @moduledoc false
  alias Wayfinder.Processor.Route

  @reserved_keywords ~w(
    break case catch class const continue debugger default delete do else
    export extends false finally for function if import in instanceof new null
    return super switch this throw true try typeof var void while with
  )

  @spec safe_method_name(String.t(), String.t()) :: String.t()
  def safe_method_name(name, suffix) do
    name = camelize_name(name)

    cond do
      name in @reserved_keywords ->
        name <> String.capitalize(suffix)

      String.match?(name, ~r/^\d+$/) ->
        suffix <> name

      true ->
        name
    end
  end

  @spec clean_typescript(String.t()) :: String.t()
  def clean_typescript(content) do
    content
    |> String.replace(" ,", ",")
    |> String.replace("[ ", "[")
    |> String.replace(", }", " }")
    |> String.replace("} )", "})")
    |> String.replace(" )", ")")
    |> String.replace("( ", "(")
    |> String.replace("\n\n\n", "\n\n")
    |> String.replace(~r/\n{3,}/, "\n\n")
  end

  @spec generate_route_file([Route.t()]) :: String.t()
  def generate_route_file(routes) do
    # TODO: Generate TypeScript content for named routes
    # Placeholder for now:
    """
    // Auto-generated by Wayfinder

    #{inspect(routes, pretty: true, limit: :infinity)}
    """
    |> clean_typescript()
  end

  @spec generate_action_file([Route.t()]) :: String.t()
  def generate_action_file(actions) do
    # TODO: Generate TypeScript content for controller actions
    # Placeholder for now:
    """
    // Auto-generated by Wayfinder

    #{inspect(actions, pretty: true, limit: :infinity)}
    """
    |> clean_typescript()
  end

  defp camelize_name(name) do
    Macro.camelize(name)
    |> then(fn str -> String.downcase(String.first(str)) <> String.slice(str, 1..-1//1) end)
  end
end
